packages:
  - 'templates/angular-webpack/'
  # - 'templates/astro/'
  - 'templates/kolibri-library/app/'
  - 'templates/kolibri-library/components/'
  - 'templates/kolibri-library/components/adapters/angular/'
  - 'templates/kolibri-library/components/adapters/react/'
  - 'templates/kolibri-library/components/adapters/vue/'
  - 'templates/kolibri-library/schema/'
  - 'templates/kolibri-library/theme/'
  - 'templates/kolibri-theme/'
  # - 'templates/next.js/'
  # - 'templates/preact-webpack/'
  - 'templates/react-vite/'
  - 'templates/react-webpack/'
  - 'templates/solid-webpack/'
  - 'templates/static-page/'
  - 'templates/svg2font/'
  - 'templates/vue-vite/'
  - 'templates/vue-webpack/'
